server:
  port: 8081
spring:
  application:
    name: ifamily-user
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ifamily_user?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource:
              ERROR