server:
  port: 8888
spring:
  application:
    name: ifamily-gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ifamily-auth
          uri: lb://ifamily-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: ifamily-acl
          uri: lb://ifamily-acl
          predicates:
            - Path=/acl/**
        - id: ifamily-user
          uri: lb://ifamily-user
          predicates:
            - Path=/user/**
        - id: ifamily-backend
          uri: lb://ifamily-backend
          predicates:
            - Path=/backend/**
        - id: ifamily-manager
          uri: lb://ifamily-manager
          predicates:
            - Path=/manager/**
        - id: ifamily-genealogy
          uri: lb://ifamily-genealogy
          predicates:
            - Path=/genealogy/**
        - id: ifamily-social
          uri: lb://ifamily-social
          predicates:
            - Path=/social/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9420/rsa/public"
secure:
  ignore:
    urls:
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/*/*.map"
      - "/webjars/**"
      - "/auth/oauth/token"
      - "/*/api/**"