server:
  port: 8888
spring:
  application:
    name: ifamily-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: ifamily-user
          uri: http://localhost:8081
          predicates:
            - Path=/*/user/**
        - id: ifamily-manager
          uri: http://localhost:8082
          predicates:
            - Path=/*/manager/**
logging:
  level:
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource:
              ERROR