server:
  port: 8888
spring:
  application:
    name: ifamily-gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ifamily-auth
          uri: lb://ifamily-auth
          predicates:
            - Path=/ifamily-auth/**
          filters:
            - StripPrefix=1
        - id: ifamily-user
          uri: lb://ifamily-user
          predicates:
            - Path=/ifamily-user/**
          filters:
            - StripPrefix=1
        - id: ifamily-admin
          uri: lb://ifamily-admin
          predicates:
            - Path=/ifamily-admin/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9420/rsa/public'
secure:
  ignore:
    urls:
      - "/ifamily-auth/oauth/token"