module.exports = {
    // title of the website
    title: '百家谱',
    // website style settings show on the right panel
    showSettings: true,
    // operation log show on the navbar tag views
    tagsView: true,
    // website logo on the left top navbar
    sidebarLogo: true,
    // fixed the top header
    fixedHeader: true,
    // error log generated by Vue
    errorLog: ['production', 'development']
}
