server:
  port: 8825
spring:
  application:
    name: ifamily-manager
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/ifamily_manager?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  mail:
    host: smtp.126.com
    username: springbear2020@126.com
    password: ZGHBMRHNKHLJVJBU
    default-encoding: UTF-8